BIDS working

diff --git a/gear/prfsynth/run b/gear/prfsynth/run
--- a/gear/prfsynth/run
+++ b/gear/prfsynth/run
@@ -1,60 +1,143 @@
 #! /bin/bash
 #
-#
+# The run script for the prfsynth docker.
+################################################################################
+set +o verbose   # Command echo off
+
+# If run in debug mode, just exec bash:
+if [ "$1" = "DEBUG" ]
+then exec /bin/bash
+else . /etc/profile.d/conda.sh
+     conda activate base
+fi
+
+# Some variables and functions #################################################
 
 CONTAINER="[garikoitz/prfsynth]"
-echo -e "$CONTAINER  Initiated"
-
-
+MCR_ROOT=/opt/mcr/v95/
 # Built to flywheel-v0 spec.
 FLYWHEEL_BASE=/flywheel/v0
-MCR_ROOT=/opt/mcr/v95/
-OUTPUT_DIR=$FLYWHEEL_BASE/output
+OUTPUT_DIR="$FLYWHEEL_BASE"/output
+INPUT_DIR="$FLYWHEEL_BASE"/input
+CONFIG_FILE="$INPUT_DIR"/config.json
+# How we print to stdout:
+function note {
+    echo "$CONTAINER" "   " "$*"
+}
+function die {
+    echo "<ERROR>" "$CONTAINER" "   " "$*"
+    exit 1
+}
+# How we get the tr-len out of a nifti:
+function getTRLEN {
+    TRLEN="`python -c \"import neuropythy as ny, pimms; im = ny.load('$1', to='image'); print(pimms.mag(ny.to_image_spec(im)['voxel_duration'], 'seconds')); exit();\"`"
+}
+function getFRAMES {
+    FRAMES="`python -c \"import neuropythy as ny; im = ny.load('$1', to='image'); print(np.squeeze(im.dataobj).shape[-1]); exit();\"`"
+}
+function writeEventsFile {
+    EVENTS_FILE="$1" STIM_FILE="$2" python <<EOF
+from __future__ import print_function
+import neuropythy as ny, sys, os, pimms, numpy as np
+stimfl = os.environ['STIM_FILE']
+im = ny.load(stimfl, to='image')
+rows = np.squeeze(im.dataobj).shape[-1]
+trlen = pimms.mag(ny.to_image_spec(im)['voxel_duration'], 'seconds')
+with open(os.environ['EVENTS_FILE'], 'w') as f:
+    print('onset','duration','stim_file','stim_file_index', sep='\t', file=f)
+    for ii in range(rows):
+        print('%7.3f\t%7.3f\t%s\t%d' % (trlen * ii, trlen, stimfl, ii+1), file=f)
+sys.exit(0)
+EOF
+}
 
 
+# The Script ###################################################################
+
+# Announce ourselves:
+note "Initialized."
 # Make sure that /output directory exists
-if [[ ! -d "$OUTPUT_DIR" ]]
-    then
-        echo "$CONTAINER  $OUTPUT_DIR not found!"
-        exit 1
-fi
-
-
-# Set paths to input files
-CONFIG_FILE=${FLYWHEEL_BASE}/input/config.json
-
-
+[ -d "$OUTPUT_DIR" ] || die "Output directory ($OUTPUT_DIR) not found!"
 # Run the Matlab executable
 time /compiled/run_synthBOLDgenerator.sh "${MCR_ROOT}" "${CONFIG_FILE}" "${OUTPUT_DIR}"
-
-
 # Check exit status
-exit_status=$?
-if [[ $exit_status != 0 ]]; then
-  echo -e "$CONTAINER  An error occurred during execution of the Matlab executable. Exiting!"
-  exit 1
-fi
-
-
+[ $? = 0 ] || die "An error occurred during execution of the Matlab executable. Exiting!"
 # Get a list of the files in the output directory
-# outputs=$(find $OUTPUT_DIR/* -maxdepth 0 -type f)
-outputs=$(find $OUTPUT_DIR/* )
+outputs=$(find "$OUTPUT_DIR" -type f -name '*_Stim.nii.gz')
+[ -z "$outputs" ] && die "No results found in output directory... Exiting"
+# Make sure there's a BIDS directory:
+[ -d "$OUTPUT_DIR"/BIDS ] || {
+    note "Making BIDS directory: $OUTPUT_DIR/BIDS"
+    mkdir -p "$OUTPUT_DIR"/BIDS/
+}
+BIDS_DIR="$OUTPUT_DIR/BIDS"
+# synth datasets are identified by the _Stim.nii.gz extension; not sure we
+# are planning to support names with spaces in them anyway, but this code
+# will prevent wierd name mangling in that case:
+TMPFL="`mktemp`"
+find "$OUTPUT_DIR" -name '*_Stim.nii.gz' -type f -exec echo '{}' ';' > "$TMPFL"
+OIFS="$IFS"
+IFS=$'\n' read -d '' -r -a STIMFILES < "$TMPFL"
+IFS="$OIFS"
 
-
-# If outputs exist, generate metadata, and exit
-if [[ -z $outputs ]]; then
-  echo "$CONTAINER  No results found in output directory... Exiting"
-  exit 1
-else
-  cd $OUTPUT_DIR
-  echo -e "$CONTAINER  Available synth datasets: `ls`"
-  echo -e "$CONTAINER  Done!"
+if [ ${#STIMFILES[@]} = 0 ]
+then note "No potential synth datasets found."
+else note "Available synth datasets: ${STIMFILES[@]}"
+     DDFL="$BIDS_DIR"/"dataset_description.json"
+     if [ -a "$DDFL" ]
+     then note "  * (Found existing dataset_description.json; this file left untouched)"
+     else # Go ahead and make a dataset description:
+          mkdir -p "$BIDS_DIR"
+          echo '{' > "$DDFL"
+          echo '   "Name": "PRFSynth Dataset",' >> "$DDFL"
+          echo '   "BIDSVersion": "1.0.1",' >> "$DDFL"
+          echo '   "Authors": ["Garikoitz Lerma-Usabiaga",' >> "$DDFL"
+          echo '               "Noah C. Benson",' >> "$DDFL"
+          echo '               "Jonathan Winawer",' >> "$DDFL"
+          echo '               "Brian Wandell"],' >> "$DDFL"
+          echo '}' >> "$DDFL"
+     fi
 fi
-
+# Actually go through the datasets:
+for SF in "${STIMFILES[@]}"
+do # Get the actual dataset name...
+   name="`basename \"$SF\" _Stim.nii.gz`"
+   ddir="`dirname \"$SF\"`"
+   dname="`basename \"$ddir\"`"
+   tt="${dname:$(( ${#name} + 1 ))}"
+   echo "BIDS-ifying Dataset ${name} ($tt)..."
+   # Make a subject and session directory and put the functional simulations
+   sub="`echo $name | tr ' ' '+'`"
+   ses="prfsynth${tt}"
+   # Move the BOLD nifti to the appropriate spot
+   BOLDFL="${BIDS_DIR}/sub-${sub}/ses-${ses}/func/sub-${sub}_ses-${ses}_task-prf_acq-normal_run-01_bold.nii.gz"
+   mkdir -p "$BIDS_DIR"/sub-${sub}/ses-${ses}/func \
+    && mv "$ddir"/"${name}.nii.gz" "$BOLDFL"
+   # Make a stimulus directory and put the stimulus there
+   STIMFL="$BIDS_DIR/stimuli/sub-${sub}_ses-${ses}_task-prf_apertures.nii.gz"
+   mkdir -p "$BIDS_DIR"/stimuli \
+    && mv "$SF" "$STIMFL"
+   # Make the BOLD JSON sidecar file
+   JSONFL="$BIDS_DIR"/sub-${sub}/ses-${ses}/func/sub-${sub}_ses-${ses}_task-prf_acq-normal_run-01_bold.json
+   getTRLEN "$BOLDFL"
+   echo '{' > "$JSONFL"
+   echo '   "RepetitionTime": ${TRLEN},' >> "$JSONFL"
+   echo '   "TaskName": "prf"' >> "$JSONFL"
+   echo '}' >> "$JSONFL"
+   # Make a derivatives directory and put the extra json there
+   mkdir -p "${BIDS_DIR}/derivatives/prfsynth/sub-${sub}/ses-${ses}" \
+    && mv "$ddir"/"${name}.json" "$BIDS_DIR"/derivatives/prfsynth/sub-${sub}/ses-${ses}/sub-${sub}_ses-${ses}_task-prf_acq-normal_run-01_bold.json
+   # Make an events file for the stimulus
+   EVENTSFL="${BIDS_DIR}/sub-${sub}/ses-${ses}/func/sub-${sub}_ses-${ses}_task-prf_events.tsv"
+   writeEventsFile "$EVENTSFL" "$STIMFL"
+   # That's all!
+done
 
 # Handle permissions of the outputs
-chmod -R 777 $OUTPUT_DIR
-
+find "$OUTPUT_DIR" -type d -exec chmod 755 '{}' ';'
+find "$OUTPUT_DIR" -type f -exec chmod 644 '{}' ';'
+#chmod -R 755 "$OUTPUT_DIR"/*
+echo -e "$CONTAINER  Done!"
 
 # Exit
 exit 0
